---
# vars file for client-setup

country: Europe/Madrid
hostname: managed-by-ansible
motd: client.j2

packages:
  - vim
  - telnet
  - htop
  - iotop
  - atop
  - mc
  - traceroute
  - unzip

dirnames:
  - foo
  - bar
  - baz

filenames:
  - foo-file1
  - foo-file2
  - bar-file1
  - bar-file2
  - baz-file1
  - baz-file2

