---
# tasks file for client-setup

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"

- name: Set custom timezone
  timezone:
    name: "{{ country }}"

- name: Set custom hostname
  hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Get current user
  shell: whoami
  register: current_user
  changed_when: false

- name: Set custom MOTD
  template:
    src: "{{ motd }}"
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Create directories
  file:
    path: "/opt/academy-{{ item }}"
    state: directory
  loop: "{{ dirnames }}"

- name: Copy files to corresponding directories
  copy:
    src: "roles/client-setup/files/{{ item }}"
    dest: "/opt/academy-{{ item.split('-')[0] }}/{{ item }}"
  loop: "{{ filenames }}"

